// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPAFXDpDsSMXZBRZS-9wAuOYE8llB3PKw',
    appId: '1:888887300808:web:071cfda06c449fc76f0bfd',
    messagingSenderId: '888887300808',
    projectId: 'extreme-academy-f91ca',
    authDomain: 'extreme-academy-f91ca.firebaseapp.com',
    storageBucket: 'extreme-academy-f91ca.appspot.com',
    measurementId: 'G-G12RYGZECG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfORGYtlj5OpyCaIYfHe_OvjexEmVf9Ks',
    appId: '1:888887300808:android:948e43bd00d5e0126f0bfd',
    messagingSenderId: '888887300808',
    projectId: 'extreme-academy-f91ca',
    storageBucket: 'extreme-academy-f91ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4qKgoSYYEninrHgmXC5J6_xsGrQpGiQs',
    appId: '1:888887300808:ios:17e303753099dec36f0bfd',
    messagingSenderId: '888887300808',
    projectId: 'extreme-academy-f91ca',
    storageBucket: 'extreme-academy-f91ca.appspot.com',
    iosBundleId: 'com.learningApp.learningAnglishApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4qKgoSYYEninrHgmXC5J6_xsGrQpGiQs',
    appId: '1:888887300808:ios:e39ea5c11aef179a6f0bfd',
    messagingSenderId: '888887300808',
    projectId: 'extreme-academy-f91ca',
    storageBucket: 'extreme-academy-f91ca.appspot.com',
    iosBundleId: 'com.learningApp.learningAnglishApp.RunnerTests',
  );
}
